server:
  port: 8080
  servlet:
    context-path: /

spring:
  web:
    resources:
      static-locations: classpath:/staticResources
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: false